spring:
  application:
    name: share-sports-vendor-backend

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    generate-ddl: true
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  jwt:
    secret: ${JWT_SECRET}
    access-token-validity: ${JWT_AT}  # 1 hour in milliseconds
    refresh-token-validity: ${JWT_RT}  # 7 days in milliseconds

  mail:
    host: smtp.gmail.com
    port: 587
    username: tnbin98@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: -1
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

logging:
  level:
    org.example.sharesportsvendorbackend: DEBUG

server:
  port: 9090
